version: '3'

services:
  oracle:
    image: oracle/instantclient11.2
  django:
    build: .
    command: gunicorn offer_universities.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - oracle
