# Generated by Django 2.2.6 on 2019-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('city', models.ForeignKey(on_delete=None, related_name='universities', to='universities.City')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_subject', models.CharField(max_length=191)),
                ('second_subject', models.CharField(max_length=191)),
                ('profession', models.ForeignKey(on_delete=None, related_name='subjects', to='universities.Profession')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='university',
            field=models.ForeignKey(on_delete=None, related_name='professions', to='universities.University'),
        ),
    ]
