# Generated by Django 2.2.6 on 2019-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='first_subject',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='second_subject',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
