# Generated by Django 2.2.6 on 2019-11-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='professions',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='university',
            table='universities',
        ),
    ]
