# Generated by Django 2.2.6 on 2019-11-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20191124_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='code',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='profession',
            name='first_subject',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='profession',
            name='second_subject',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.IntegerField(),
        ),
    ]
