# Generated by Django 2.2.6 on 2019-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20191126_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='first_subject',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='second_subject',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='university',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='university',
            name='site',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='code',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=191, null=True)),
                ('name', models.CharField(max_length=191, null=True)),
                ('first_subject', models.CharField(max_length=191, null=True)),
                ('second_subject', models.CharField(max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('university', models.ForeignKey(on_delete=None, related_name='specialities', to='universities.University')),
            ],
            options={
                'db_table': 'specialities',
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=None, related_name='professions', to='universities.Speciality'),
        ),
    ]
