# Generated by Django 2.2.6 on 2019-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_auto_20191209_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='grant_kaz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='grant_rus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='total_grant',
            field=models.IntegerField(null=True),
        ),
    ]
