# Generated by Django 2.2.6 on 2019-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20191209_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='city',
            name='name_kz',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_kz',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_kz',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='name_ru',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_kz',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(max_length=191, null=True),
        ),
    ]
