# Generated by Django 2.2.6 on 2019-12-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_auto_20191209_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
